<?php
/*
*   Resumen de movimientos de Anexo Transaccional. segun tipo de retencion
*   @package    Dimm
*   @subpackage Reportes
*   @version    1.0
*   @date       Jul/03/06
*
*
**/
//header("Content-Type: application/vnd.ms-excel");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
?>
<html>
<head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<link rel="stylesheet" type="text/css" href="../Themes/Cobalt/Style.css">
<title>RESUMEN DE COMPRAS</title>
<style type="text/css">
<!--
.head1 {background: #CC9933; height:22px; color: #FFFFFF; font-size: 9pt; font-weight: 500=medium; text-align: center}
.sub1 {background: #C8B588; height:22px; color: #FFFFFF; font-size: 9pt; font-weight: 500=medium; text-align: center}
.data1 {background: #EEEECC; font-size: 9pt}
.data2 {background: #CCCCCC; font-size: 9pt}
.numerico {text-align:right; width:200}
.periodo {width: 150; }
.simple  {}
TD { nowrap:true}

/*printer friendly styles*/
.border {border: solid 1px #CCCCCC}
.TLB {border: solid 1px #CCCCCC; border-right: none}
.TB {border-top:  solid 1px #CCCCCC; border-bottom:  solid 1px #CCCCCC}
.TRB {border: solid 1px #CCCCCC; border-left: none}
.T {border-top: solid 1px #CCCCCC}
.L {border-left: solid 1px #CCCCCC}
.B {border-bottom: solid 1px #CCCCCC}
.LR {border-left: solid 1px #CCCCCC; {border-right: solid 1px #CCCCCC}
.LB {border-left: solid 1px #CCCCCC; {border-bottom: solid 1px #CCCCCC}
.LRB {border: solid 1px #CCCCCC; border-top: none}

/* End of style section. Generated by AceHTML at 16/08/03 10:14:34 */
-->
</style>
</head>
<body bgcolor="#fffff7" link="#000000" alink="#ff0000" vlink="#000000" text="#000000" class="CobaltPageBODY" style="PADDING-RIGHT: 0px; PADDING-LEFT: 0px; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; magin: 0; spacing: 0" bottommargin="0" nowrap leftmargin="0" topmargin="17" rightmargin="0" marginwidth="0" marginheight="0">
<?php
/*
*   InTrTr_rescomprprov.php: Resumen de Transacciones Compras de Inventario
*   @author     Fausto Astudillo
*   @param      string 		pQryTar  Condición de búsqueda
*   @output     contenido pdf del reporte.
*/
include_once("../LibPhp/LibInc.php");
include_once('baaGrid.php');
error_reporting(ALL);
/**
*   Definicion de Query que selecciona los datos a presentar
*   access  public
*   @param   object   $db Refrencia a la conexxion de BD
*   @param  string    $pQry Condicion de busqueda
*   @return object    Referencia del Recordset.
*/
function &fDefineQry(&$db, $pQry=false){
    $alSql[]   = "DROP TABLE IF EXISTS tmp_retenc ; ";
    $alSql[]   = "CREATE  TABLE tmp_retenc (
                    ID INTEGER(10),
                    retCodigo   INTEGER(4),
                    retBase     DECIMAL(12,2),
                    retValor    DECIMAL(12,2)
                    ); ";
                    
    $alSql[]= "INSERT INTO tmp_retenc
                    SELECT ID, codRetAir, baseImpAir, valretAir
                    FROM fiscompras " .
                    (($pQry)?  " WHERE "  . $pQry : "") . "; ";

    $alSql[]= "INSERT INTO tmp_retenc
                    SELECT ID, codRetAir2, baseImpAir2, valretAir2
                    FROM fiscompras " .
                    (($pQry)?  " WHERE "  . $pQry : "") . ";; ";

    $alSql[]= "INSERT INTO tmp_retenc
                    SELECT ID, codRetAir3, baseImpAir3, valretAir3
                    FROM fiscompras " .
                    (($pQry)?  " WHERE "  . $pQry : "") . ";;; ";

    $alSql2 = "SELECT  concat(year(fechaRegistro),'-', left(monthname(fecharegistro),3)) as PERIODO_ ,
                	concat(tra.tab_codigo, '-', tra.tab_Descripcion) AS TRANSACCION,
                	concat(tir.tab_codigo, '-', tir.tab_descripcion) AS RETENCION,
                	sum(retBase) AS `BASE.IMPON`,
                	sum(retValor)AS `VALOR`
                FROM fiscompras fco
			JOIN tmp_retenc ON tmp_retenc.ID = fco.ID
                	LEFT JOIN fistablassri tco ON tco.tab_CodTabla = '2'  AND fco.tipoComprobante +0 = tco.tab_Codigo
                	LEFT JOIN fistablassri tra ON tra.tab_CodTabla = 'A'  AND fco.tipoTransac = tra.tab_Codigo
                	JOIN fistablassri tir ON tir.tab_CodTabla = '10'  AND retCodigo = tir.tab_Codigo " .
            ( ($pQry) ? " WHERE "  . $pQry : " " ) .
            " GROUP BY 1,2,3
             ORDER  BY 1,2,3 ";
    fSql($db, $alSql);
    return $alSql2;
}

/**
*   Definicion de Query que selecciona los datos de IVA a presentar
*   access  public
*   @param   object   $db Refrencia a la conexxion de BD
*   @param  string    $pQry Condicion de busqueda
*   @return object    Referencia del Recordset.
*/
function &fDefineQryIva(&$db, $pQry=false){

    $alSql2 = "SELECT  concat(year(fechaRegistro),'-', left(monthname(fecharegistro),3)) as PERIODO ,
                    sum(baseImponible) AS IMPONIB,
                    sum(baseImpGrav) AS GRAVABLE,
                    porcentajeIva AS COD_IVA,
                    sum(montoIva) AS VALOR_IVA,
                    sum(montoIvaBienes) IMPON_IVA_BIENES,
                    porRetBienes COD_RETB,
                    sum(valorRetBienes) VALOR_RET_BIENES,
                    sum(montoIvaServicios) IMPON_IVA_SERV,
                    porRetServicios COD_RETS,
                    sum(valorRetServicios) VALOR_RET_SERV
                FROM fiscompras
                 " .
            ( ($pQry) ? " WHERE "  . $pQry : " " ) .
            " GROUP  BY 4,7,10 ORDER  BY 4,7,10 ";
    fSql($db, $alSql);
    return $alSql2;
}
/** Process the Report Header
*   You can access any property / method from ezPdfReport Object using var $rpt and group data from variable $group received as parameters
*   To put any text, line, rectangle, etc into your report, use the object $rpt->pdf and its "ez functions" (see ezPdf manual),
*   be care of functions that don´t move the insertion point to void text overlapping
*   Note: This function REDEFINES the top margin.
*   @access public
*   @param  object      $rpt        Reference to current report object
*   @param  object      $hdr        Reference to current header report object
*   @return void
*/

//--------------------------------------------------------------------------------------------------------------------
//                          Procesamiento
//--------------------------------------------------------------------------------------------------------------------
//
//session_start();
$db = NewADOConnection("mysql");
//include("AdoDBIni.php");
$db->SetFetchMode(ADODB_FETCH_ASSOC);
$db->Connect(DBSRVR, DBUSER, DBPASS, DBNAME) or die("<BR> <BR> No hay acceso al servidor");
$db->debug=fGetParam('pAdoDbg', 0);
set_time_limit (0) ;
$pQry= fGetParam('pQryCom', 0);
$sltext="";
$pAnio = fGetParam('s_Anio', 0);
$pMes = fGetParam('s_Mes', 0);
ob_start();
if ($pAnio >0 and $pMes >0 ) {
    $pQry = " YEAR(fechaRegistro) = $pAnio AND month(fechaRegistro) = $pMes";
    $slSql=fDefineQry($db, $pQry );
	$goGrid = new baaGrid ($slSql, DB_MYSQL);
	$goGrid->setTableAttr('border="1" nowrap align="center" cellspacing="1" width="'. $ilTabW . '"');
	$goGrid->showErrors(); // just in case
	$goGrid->setHeaderClass('CobaltColumnTD');
	$goGrid->setRowClass('CobaltDataTD,CobaltAltDataTD');
	$goGrid->externHead=$slHead1;
//	$goGrid->showColNumbers(true);
	$goGrid->setWidth( 0, 150);
	$goGrid->setWidth( 1, 200);
	$goGrid->setWidth( 2, 1000);
	$goGrid->setWidth( 3, 150);
	$goGrid->setWidth( 4, 150);
	$goGrid->setColClass("periodo,simple,simple,numerico,numerico");
	for ($j=7; $j<=17; $j++) 	{
		$goGrid->setWidth($j, 150);
		$goGrid->setDecPlaces($j, 2);
		$goGrid->setTotal($j, 2);
	}
	$goGrid->setTotal(4, 2);
	$goGrid->setTotal(4, 2);
	$goGrid->setOnChange(0,1,2);
	$goGrid->setOnChange(1,1,2);
/*	$goGrid->setOnChange(2,0,0);
    $goGrid->setOnChange(3,0,0);
	$goGrid->setOnChange(4,0,0);
   */
    $goGrid->setSubTotalClass('sub1');
//	echo $goGrid->externHead;
	$goGrid->display();


    $slSql=fDefineQryIva($db, $pQry );
	$goGrid = new baaGrid ($slSql, DB_MYSQL);
	$goGrid->setTableAttr('border="1" nowrap align="center" cellspacing="1" width="'. $ilTabW . '"');
	$goGrid->showErrors(); // just in case
	$goGrid->setHeaderClass('CobaltColumnTD');
	$goGrid->setRowClass('CobaltDataTD,CobaltAltDataTD');
	$goGrid->externHead=$slHead1;
//	$goGrid->showColNumbers(true);
	$goGrid->setWidth( 0, 150);
/**	$goGrid->setWidth( 1, 150);
	$goGrid->setWidth( 2, 150);
	$goGrid->setWidth( 3, 150);
	$goGrid->setWidth( 4, 150);
	$goGrid->setWidth( 5, 150);
	$goGrid->setWidth( 6, 150);
	$goGrid->setWidth( 7, 150);
	$goGrid->setWidth( 8, 150);
	$goGrid->setWidth( 9, 150);
	$goGrid->setWidth( 10, 150);
	$goGrid->setWidth( 11, 150); **/
	$goGrid->setColClass("periodo,numerico,numerico,numerico,numerico,numerico,numerico,numerico,numerico,numerico,numerico");
	for ($j=1; $j<=11; $j++) 	{
		$goGrid->setWidth($j, 150);
		$goGrid->setDecPlaces($j, 2);
	}
	$goGrid->setDecPlaces(3, 0);
	$goGrid->setDecPlaces(6, 0);
	$goGrid->setDecPlaces(9, 0);
	
	$goGrid->setTotal(1, 2);
	$goGrid->setTotal(2, 2);
	$goGrid->setTotal(4, 2);
	$goGrid->setTotal(5, 2);
	$goGrid->setTotal(7, 2);
	$goGrid->setTotal(8, 2);
	$goGrid->setTotal(10, 2);
	
	$goGrid->setOnChange(0,1,0);
	$goGrid->setOnChange(3,1,0);
//	$goGrid->setOnChange(6,1,0);
//	$goGrid->setOnChange(9,1,0);
    $goGrid->setSubTotalClass('CobaltColumnTD');
//	echo $goGrid->externHead;
	$goGrid->display();

	ob_end_flush();
	}
else {
        echo "DEBE ELEGIR UN AÑO Y MES ";
}
?>
