<html>
<head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Content-Type" content="application/vnd.ms-excel">
<link rel="stylesheet" type="text/css" href="../Themes/Cobalt/Style.css">
<title>RESUMEN</title>
<style type="text/css">
<!--
.head1 {background: #CC9933; height:22px; color: #FFFFFF; font-size: 9pt; font-weight: 500=medium; text-align: center}
.sub1 {background: #C8B588; height:22px; color: #FFFFFF; font-size: 9pt; font-weight: 500=medium; text-align: center}
.data1 {background: #EEEECC; font-size: 9pt}
.data2 {background: #CCCCCC; font-size: 9pt}

/*printer friendly styles*/
.border {border: solid 1px #CCCCCC}
.TLB {border: solid 1px #CCCCCC; border-right: none}
.TB {border-top:  solid 1px #CCCCCC; border-bottom:  solid 1px #CCCCCC}
.TRB {border: solid 1px #CCCCCC; border-left: none}
.T {border-top: solid 1px #CCCCCC}
.L {border-left: solid 1px #CCCCCC}
.B {border-bottom: solid 1px #CCCCCC}
.LR {border-left: solid 1px #CCCCCC; {border-right: solid 1px #CCCCCC}
.LB {border-left: solid 1px #CCCCCC; {border-bottom: solid 1px #CCCCCC}
.LRB {border: solid 1px #CCCCCC; border-top: none}

/* End of style section. Generated by AceHTML at 16/08/03 10:14:34 */
-->
</style>
</head>
<body bgcolor="#fffff7" link="#000000" alink="#ff0000" vlink="#000000" text="#000000" class="CobaltPageBODY" style="PADDING-RIGHT: 0px; PADDING-LEFT: 0px; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; magin: 0; spacing: 0" bottommargin="0" nowrap leftmargin="0" topmargin="17" rightmargin="0" marginwidth="0" marginheight="0">
<?php
/** Generacion de tabla resumen de embarque, por fecha, marca, productor
*   @author   	fausto astudillo
*	@Created	Jul/22/05
**/
include_once("../LibPhp/LibInc.php");
include_once('baaGrid.php');
error_reporting(ALL);
/**
*   Definicion de Query que selecciona los datos a presentar
*   @access  public
*   @param   object   Refrencia a la conexxion de BD
*   @param   integer  $pSem		Semana a procesar 
*   @return  object   Referencia del Recordset.
*/
function &fDefineQry(&$db, $pSem=0, $pEmb=false){
    global $gsTitGeneral;
    global $goGrid;
    IF(!$db->Execute( "DROP TABLE IF EXISTS tmp_dias")) fErrorPage('','NO SE PUDO ELIMINAR DATOS TEMPORALES DE FECHAS', true,false);
    IF(!$db->Execute( "DROP TABLE IF EXISTS tmp_marcas")) fErrorPage('','NO SE PUDO ELIMINAR DATOS TEMPORALES DE MARCAS', true,false);

/**			Analizar el numero de subcolumnas por cada dia 
**/
	$slSql = "SELECT tac_fecha, date_format( tac_fecha, '%b-%d') as tmp_fecha, count(*) as tmp_cols 
				FROM (
					SELECT DISTINCT  tac_fecha, tad_codmarca
						FROM liqtarjacabec  JOIN liqtarjadetal on tad_numtarja = tar_numtarja
		     								JOIN genparametros on par_clave = 'IMARCA' and par_secuencia = tad_codmarca
					WHERE tac_semana =  " . $pSem . ($pEmb>0 ? " AND tac_refOperativa = " . $pEmb : "") . " AND
					      (tad_cantrecibida - tad_cantrechazada  ) <> 0
					ORDER BY 1, 2 ) tmp
				GROUP BY 1, 2
				ORDER BY 1 "; 
	$rs = $db->Execute($slSql);
	if(!$rs) fErrorPage('',"NO SE PUDO ACCEDER AL RESUMEN DE DIAS " . $slSql, true, false);
//	$slHead1="<th>\n";
    while ($rec = $rs->FetchNextObject(true)) {
        $slHead1 .= "	<th align='center' colspan= '" . $rec->TMP_COLS . "' > " . $rec->TMP_FECHA . "</th>\n";
    }			
//	$slHead1.="</th>\n";
	$slSql = "SELECT distinct tac_fecha, tad_codmarca, left(par_descripcion,5) as tmp_descr
					FROM liqtarjacabec join liqtarjadetal on tad_numtarja = tar_numtarja
		     		JOIN genparametros on par_clave = 'IMARCA' and par_secuencia = tad_codmarca
				 WHERE tac_semana = " . $pSem . ($pEmb>0 ? " AND tac_refOperativa = " . $pEmb : "") . " AND
					   (tad_cantrecibida - tad_cantrechazada  ) <> 0
			     ORDER BY 1, 2 ";
;
	$rs = $db->Execute($slSql);
	if(!$rs) fErrorPage('',"NO SE PUDO ACCEDER AL RESUMEN DE MARCAS " . $slSql, true, false);
	$slHead="";
	$slPivt = "";
	$i=0;
	$ilWidth='50';
	$ilCodW='40';
	$ilNomW='250';
	$ilZonW='75';
    while ($rec = $rs->FetchNextObject(true)) {
	   	++$i;
        $slHead .= "<th style='width:" . $ilWidth . "px'>" . strtoupper($rec->TMP_DESCR) . "</th>\n" ;
		$slPivt .= (strlen($slPivt) ? ", " : "" ) . 
				   "SUM(IF (tac_fecha = '" . $rec->TAC_FECHA . "' and tad_codmarca = " . $rec->TAD_CODMARCA .  
				   ",(tad_cantrecibida - tad_cantrechazada  ), 0)) as C" . $i . "\n";
    }
    $slHead1="<tr class='CobaltColumnTD'>\n" .
    			"<th rowspan='2' style='width: " . $ilZonW . "px'>ZONA</th>\n" .
				"<th rowspan='2' style='width: " . $ilCodW . "px'>COD.</th>\n" .
			 	"<th rowspan='2' style='width: " . $ilNomW . "px'>NOMBRE</th>\n" . $slHead1 .
				"<th rowspan='2' style='width: " . $ilWidth . "px'>TOTAL</th>\n" .  
			 "</tr>\n" .
			 "<tr class='CobaltColumnTD' >" . $slHead . "</tr>";
    
	$slSql = "SELECT tac_zona, tac_embarcador, ucase(concat(left(per_apellidos,12), ' ' , left(per_nombres,12))) as tmp_productor, " .
			 		$slPivt . ($slPivt?",":"") . " SUM((tad_cantrecibida - tad_cantrechazada  )) as CT ".
			 "FROM liqtarjacabec 
			 		JOIN liqtarjadetal on tad_numtarja = tar_numtarja
					JOIN conpersonas on per_codauxiliar = tac_embarcador
				WHERE tac_semana = " . $pSem . ($pEmb>0 ? " AND tac_refOperativa = " . $pEmb : "") .
			 " GROUP BY 1,2,3
			  ORDER BY 1,3 ";
	ob_start();
	echo "<DIV class='CobaltFormHeaderFont' align:'center' style='align:center text-align:center'>$gsTitGeneral </DIV>";
//	echo "<table>$slHead1</table>";
	$ilTabW = $ilZonW + $ilCodW  + $ilNomW  + ($ilWidth * ($i+1));
	$goGrid = new baaGrid ($slSql, DB_MYSQL);
//	$goGrid->setHeadings("COD., NOMBRE, " . $slHead);
	$goGrid->setTableAttr('border="1" align="center" cellspacing="1" width="'. $ilTabW . '"');
	$goGrid->showErrors(); // just in case
	$goGrid->setHeaderClass('CobaltColumnTD');
	$goGrid->setRowClass('CobaltDataTD,CobaltAltDataTD');
	$goGrid->setWidth(0, $ilZonW);
	$goGrid->setWidth(1, $ilCodW);
	$goGrid->setWidth(2, $ilNomW);
	for ($j=3; $j<=($i+3);$j++) 	{
		$goGrid->setWidth($j, $ilWidth);
		$goGrid->setDecPlaces($j,0);
		$goGrid->setTotal($j,0);
		} 
	$goGrid->showHeadings=false;
	$goGrid->externHead=$slHead1;
//	Subtotales
    $goGrid->setOnChange(0, 1);
    $goGrid->setSubTotalClass('sub1');
//	echo $goGrid->externHead;
	$goGrid->display();
	ob_end_flush();
}
//--------------------------------------------------------------------------------------------------------------------
//                          Procesamiento
//--------------------------------------------------------------------------------------------------------------------
//

//session_start();
$db = NewADOConnection("mysql");
//include("AdoDBIni.php");
$db->SetFetchMode(ADODB_FETCH_ASSOC);
$db->Connect(DBSRVR, DBUSER, DBPASS, DBNAME) or die("<BR> <BR> no hay acceso al servidor");
$db->debug=fGetParam('pAdoDbg', 0);
set_time_limit (0) ;
$pSem= fGetParam('pSem', 0);
$pEmb= fGetParam('pEmb', 0);
$sltext="";

if ($pEmb)
    $slText = fDBValor($db, 'liqembarques join liqbuques on buq_codBuque = emb_codVapor', "concat(buq_descripcion,'-' , emb_numviaje)", "emb_refoperativa =". $pEmb );
$gsTitGeneral="DETALLE ". ($pEmb>0? "" : "GENERAL ")  . "DE LA SEMANA " .$pSem . ($pEmb>0? " / VAPOR: " . $slText : " GENERAL") ;
fDefineQry($db, $pSem, $pEmb );
?>
