<?php
/**
*Script para incluir la cabecera en una pagina, no generada por CCS, pero de igual funcionalidad,
*con validacion de privilegios de acceso
*   @Crea   fah  Oct 10 /04
**/
    define("RelativePath", "../");
    include_once("../Common.php");
    if (!isset($_SESSION["g_user"]) || !$_SESSION["g_user"]) $_SESSION["g_retPage"] = $_SERVER['PHP_SELF'] . '?'. $_SERVER['QUERY_STRING'];
    include_once("General.inc.php");
    require_once("../LibPhp/SegLib.php");
    $iW1 = CCGetFromGet('w1',50);
    $iW2 = CCGetFromGet('w2',false);
    $iW2 = ($iW2==false)?(100 - $iW1) . "%" : $iW2 . "%" ;
    $iW1.="%";

?>
<html>
<head>
<base target="PAGINA">
<link rel="stylesheet" type="text/css" href="../Themes/Menu/Style.css">
<title> ...   </title>
<link rel="stylesheet" type="text/css" href="../Themes/Cobalt/Style.css">
<script language="JavaScript" src="../LibJava/general.js"></script>
<script language="Javascript">
function Inicio() {
    sF1=getFromurl("f1");
    sF2=getFromurl("f2");
    if (sF1) {
        window.frames[0].location.replace(sF1);
    }
    if (sF2) {
        window.frames[1].location.replace(sF1);
    }
}
window.onload = Inicio;
</script>
</head>
<body bgcolor="#ffffff" link="#000099" alink="#ff0000" vlink="#9999cc" text="#000000" class="CobaltPageBODY">
<table background="../Images/p_header.gif" border="0" style=" top-margin:15; WIDTH: 988px; BORDER-COLLAPSE: collapse; HEIGHT: 50px" cellspacing="0" cellpadding="0">
  <tr style= "BORDER-COLLAPSE: collapse;" >
    <td class="" style= "BORDER-COLLAPSE: collapse;" align="left" nowrap width="33%">
        <font color="#fdf5e6" style="FONT-SIZE: 12px">
         <?php
            echo "&nbsp;&nbsp;" .fTraeUsuario();
         ?>
        </font>
    </td>
    <td align="middle" nowrap valign="center" width="34%">
        <font color="#fdf5e6" style="FONT-WEIGHT: bold; FONT-SIZE: 12px">
         <?php
            echo $_SESSION["g_empr"] ? $_SESSION["g_empr"]: "??????"
         ?>
        </font>
 	</td>
    <td align="right" nowrap width="33%">
        <font color="#fdf5e6" style="BORDER-COLLAPSE: collapse; FONT-SIZE: 10px">
        <?php
            echo date("F j, Y, g:i a"). "&nbsp;&nbsp;";
        ?>
        </font>
    </td>
  </tr>
</table>
<iframe frameborder=0 name="myFrame" src=""
        MARGINWIDTH=0 MARGINHEIGHT=0 SCROLLING="auto"
        width="<? echo $iW1 ?>" height="520" style="float:left; background-color:#FFF777">
<iframe frameborder=0 name="myIframe1" src=""
        MARGINWIDTH=10 MARGINHEIGHT=0 SCROLLING="auto"
        width="<? echo $iW2 ?>" height="520" style=" top-margin=20; frameborder=15 solid #FFF557; background-color:#FFF557">
</iframe>
</body>
<script language="JavaScript" src="../LibJava/menu_func.js"></script>
</html>
