<?php
/*
*   Generar una tabla con los resultados de liquidacion, en formato para enviar al banco
*
*/
header("Content-Type: application/vnd.ms-excel");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
if (!isset ($_SESSION)) session_start();
define("RelativePath", "../");
require_once("../Common.php");
require_once("../LibPhp/SegLib.php");

?>
<html>
<head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<link rel="stylesheet" type="text/css" href="http://192.168.5.81/AAA/AAA_SEGURIDAD/Themes/Cobalt/Style.css">
<title>RESUMEN DE LIQUIDACIONES</title>
<style type="text/css">
<!--
.head1 {background: #CC9933; height:22px; color: #FFFFFF; font-size: 9pt; font-weight: 500=medium; text-align: center; vertical-align:top}
.sub1 {background: #C8B588; height:22px; color: #FFFFFF; font-size: 9pt; font-weight: 500=medium; text-align: center; vertical-align:top}
.data1 {background: #EEEECC; font-size: 9pt}
.data2 {background: #CCCCCC; font-size: 9pt}
TD {nowrap:true; vertical-align:top}
.CobaltColumnTD{font-weight:bold}

/*printer friendly styles*/
.border {border: solid 1px #CCCCCC}
.TLB {border: solid 1px #CCCCCC; border-right: none}
.TB {border-top:  solid 1px #CCCCCC; border-bottom:  solid 1px #CCCCCC}
.TRB {border: solid 1px #CCCCCC; border-left: none}
.T {border-top: solid 1px #CCCCCC}
.L {border-left: solid 1px #CCCCCC}
.B {border-bottom: solid 1px #CCCCCC}
.LR {border-left: solid 1px #CCCCCC; {border-right: solid 1px #CCCCCC}
.LB {border-left: solid 1px #CCCCCC; {border-bottom: solid 1px #CCCCCC}
.LRB {border: solid 1px #CCCCCC; border-top: none}

/* End of style section. Generated by AceHTML at 16/08/03 10:14:34 */
-->
</style>
</head>
<body bgcolor="#fffff7" link="#000000" alink="#ff0000" vlink="#000000" text="#000000" class="CobaltPageBODY" style="PADDING-RIGHT: 0px; PADDING-LEFT: 0px; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; magin: 0; spacing: 0" bottommargin="0" nowrap leftmargin="0" topmargin="17" rightmargin="0" marginwidth="0" marginheight="0">
<?
include_once("../LibPhp/LibInc.php");
include_once('baaGrid.php');
require_once('adodb/adodb.inc.php');
require_once('adodb/tohtml.inc.php'); 
require_once('../LibPhp/fetchUtil.class.php');
error_reporting(ALL);
/*$data_base = 'mysql';
$user = 'exportuser';
$passwd = 'Exp2008Dusal';
$host = 'localhost';
$db_name = '08_jorcorp';
*/
$data_base = DBTYPE;
$user = DBUSER;
$passwd = DBPASS;
$host = DBHOST;
$db_name = DBNAME;
$dsn = "$data_base://$user:$passwd@$host/$db_name?clientflags=65536";
$db = new FetchUtil($dsn);
//if (fGetParam("pSql", false)) $sqltext= fGetParam("pSql", false);
include_once ("GenUti.inc.php");
$pSem = fGetParam("pSem", -1);
$pEmb = fGetParam("pEmb", -1);
$pDbg = fGetParam("pAdoDbg", 0);
$db->DB->debug = $pDbg;
//$gsSqlText = "call spLiqGetMagDat($pSem, $pEmb )";
//fProcesar();
//require "../Ge_Files/GeGeGe_queryToXml.php";

//--------------------------------------------------------------------------------------------------------------------
//                          Procesamiento
//--------------------------------------------------------------------------------------------------------------------
//
/*$

*/
$gsSqlText = "call spLiqGetPagosBceRes($pSem)";
$conn = mysql_connect(DBSRVR , DBUSR , DBPASS, false, "CLIENT_MULTI_RESULTS=1");
mysql_select_db (DBNAME, $conn);
$goGrid = new baaGrid($gsSqlText);
//	$goGrid = new baaGrid ($gsSqlText, DB_MYSQL);
	$goGrid->setTableAttr('border="1" padding="4" nowrap align="center" cellspacing="1" width="'. $ilTabW . '"');
	$goGrid->showErrors(); // just in case
	$goGrid->setHeaderClass('CobaltColumnTD');
	$goGrid->setRowClass('CobaltDataTD,CobaltAltDataTD');
	//$goGrid->externHead=$slHead1;
    /*$goGrid->setHeadings("CODIGO, NOMBRE, RUC,CAJAS,PRECIO,TOTAL FRUTA,EMPAQUE PAGADO,DESCUENTO EMPAQUE, TOTAL A TRANFERIR,
                         HAS,INSCRIPCION,BANCO,CUENTA, TIPO,RECUPERACION DE VALORES,NETO LIQUIDADO"); */
    $goGrid->setHeadings("CODIGO, NOMBRE, RUC,CAJAS,PRECIO,TOTAL FRUTA,EMPAQUE PAGADO,DESCUENTO EMPAQUE, TOTAL A TRANFERIR,
                         HAS,INSCRIPCION,BANCO,CUENTA, TIPO");

	//$goGrid->showColNumbers(true);
	$goGrid->setWidth( 0, 50);
	$goGrid->setWidth( 1, 200);
	$goGrid->setWidth( 2, 120);
    $goGrid->setWidth( 3, 50);
    $goGrid->setWidth( 4, 50);
    $goGrid->setWidth( 5, 70);
    $goGrid->setWidth( 6, 70);
    $goGrid->setWidth( 7, 70);
    $goGrid->setWidth( 8, 70);
    $goGrid->setWidth( 9, 60);
    $goGrid->setWidth( 10, 80);
    $goGrid->setWidth( 11, 80);
    $goGrid->setWidth( 12, 70);
    $goGrid->setWidth( 13, 60);
    /*$goGrid->setWidth( 14, 60);
    $goGrid->setWidth( 15, 60);*/

	$goGrid->setTotal(3, 0);
	$goGrid->setTotal(4, 2);
	$goGrid->setTotal(5, 2);
	$goGrid->setTotal(6, 2);
	$goGrid->setTotal(7, 2);
	$goGrid->setTotal(8, 2);
	/*$goGrid->setTotal(14, 2);
	$goGrid->setTotal(15, 2);*/

	/*$goGrid->setOnChange(0,1,2);
	$goGrid->setOnChange(14,1,2);
    */
    $goGrid->setSubTotalClass('sub1');
//	echo $goGrid->externHead;
	$goGrid->showErrors();
	$goGrid->display();
	ob_end_flush();
?>
