<?php
header("Content-Type: application/vnd.ms-excel");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
?>
<html>
<head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Cache-Control" content="no-cache">
<meta http-equiv="Content-Type" content="application/vnd.ms-excel">
<link rel="stylesheet" type="text/css" href="../Themes/Cobalt/Style.css">
<title>RESUMEN DE COMPRAS</title>
<style type="text/css">
<!--
.head1 {background: #CC9933; height:22px; color: #FFFFFF; font-size: 9pt; font-weight: 500=medium; text-align: center}
.sub1 {background: #C8B588; height:22px; color: #FFFFFF; font-size: 9pt; font-weight: 500=medium; text-align: center}
.data1 {background: #EEEECC; font-size: 9pt}
.data2 {background: #CCCCCC; font-size: 9pt}

/*printer friendly styles*/
.border {border: solid 1px #CCCCCC}
.TLB {border: solid 1px #CCCCCC; border-right: none}
.TB {border-top:  solid 1px #CCCCCC; border-bottom:  solid 1px #CCCCCC}
.TRB {border: solid 1px #CCCCCC; border-left: none}
.T {border-top: solid 1px #CCCCCC}
.L {border-left: solid 1px #CCCCCC}
.B {border-bottom: solid 1px #CCCCCC}
.LR {border-left: solid 1px #CCCCCC; {border-right: solid 1px #CCCCCC}
.LB {border-left: solid 1px #CCCCCC; {border-bottom: solid 1px #CCCCCC}
.LRB {border: solid 1px #CCCCCC; border-top: none}

/* End of style section. Generated by AceHTML at 16/08/03 10:14:34 */
-->
</style>
</head>
<body bgcolor="#fffff7" link="#000000" alink="#ff0000" vlink="#000000" text="#000000" class="CobaltPageBODY" style="PADDING-RIGHT: 0px; PADDING-LEFT: 0px; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; magin: 0; spacing: 0" bottommargin="0" nowrap leftmargin="0" topmargin="17" rightmargin="0" marginwidth="0" marginheight="0">
<?php
/*
*   InTrTr_rescomprprov.php: Resumen de Transacciones Compras de Inventario
*   @author     Fausto Astudillo
*   @param      string 		pQryTar  Condición de búsqueda
*   @output     contenido pdf del reporte.
*/
include_once("../LibPhp/LibInc.php");
include_once('baaGrid.php');
error_reporting(ALL);
/**
*   Definicion de Query que selecciona los datos a presentar
*   access  public
*   @param   object   $db Refrencia a la conexxion de BD
*   @param  string    $pQry Condicion de busqueda
*   @return object    Referencia del Recordset.
*/
function &fDefineQry(&$db, $pQry=false){
    $slSql = "SELECT  
                concat(com_tipocomp, ' - ', com_numcomp) AS 'COMPROB.',
                com_feccontab AS FECHA,
                concat(com_emisor, '- ', b.per_Apellidos, ' ', b.per_nombres) as BODEGA,
                concat(com_codreceptor , '- ',p.per_Apellidos, ' ', p.per_nombres) as PROVEEDOR,
                SUM(IF(com_tipocomp='IB', det_costotal, 0)) AS COMPRAS,
                SUM(IF(com_tipocomp='DK', det_costotal, 0)) AS DEVOLUCIONES
            FROM genclasetran JOIN concomprobantes ON cla_aplicacion = 'IN' AND com_tipoComp = cla_tipoComp
             LEFT JOIN conpersonas b ON b.per_codauxiliar = com_emisor
             LEFT JOIN conpersonas p ON p.per_codauxiliar = com_codreceptor
             LEFT JOIN invdetalle ON det_regnumero = com_regnumero
             LEFT JOIN conactivos ON act_codauxiliar = det_coditem
             LEFT JOIN genunmedida ON uni_CodUnidad = act_unimedida
            WHERE com_tipocomp IN ('IB', 'DK')" ;

    if ($pQry) $slSql .= " AND "  . $pQry ;
    $slSql .= " GROUP BY 1,2,3,4  ORDER  BY PROVEEDOR, BODEGA, FECHA";
    return $slSql;
}
/** Process the Report Header
*   You can access any property / method from ezPdfReport Object using var $rpt and group data from variable $group received as parameters
*   To put any text, line, rectangle, etc into your report, use the object $rpt->pdf and its "ez functions" (see ezPdf manual),
*   be care of functions that don´t move the insertion point to void text overlapping
*   Note: This function REDEFINES the top margin.
*   @access public
*   @param  object      $rpt        Reference to current report object
*   @param  object      $hdr        Reference to current header report object
*   @return void
*/

//--------------------------------------------------------------------------------------------------------------------
//                          Procesamiento
//--------------------------------------------------------------------------------------------------------------------
//
//session_start();
$db = NewADOConnection("mysql");
//include("AdoDBIni.php");
$db->SetFetchMode(ADODB_FETCH_ASSOC);
$db->Connect(DBSRVR, DBUSER, DBPASS, DBNAME) or die("<BR> <BR> No hay acceso al servidor");
$db->debug=fGetParam('pAdoDbg', 0);
set_time_limit (0) ;
$pQry= fGetParam('pQryCom', 0);
$sltext="";

$slSql=fDefineQry($db, $pQry );

	$goGrid = new baaGrid ($slSql, DB_MYSQL);
	$goGrid->setTableAttr('border="1" align="center" cellspacing="1" width="'. $ilTabW . '"');
	$goGrid->showErrors(); // just in case
	$goGrid->setHeaderClass('CobaltColumnTD');
	$goGrid->setRowClass('CobaltDataTD,CobaltAltDataTD');
/*	$goGrid->setWidth(0, $ilZonW);
	$goGrid->setWidth(1, $ilCodW);
	$goGrid->setWidth(2, $ilNomW);
	for ($j=3; $j<=($i+3);$j++) 	{
		$goGrid->setWidth($j, $ilWidth);
		$goGrid->setDecPlaces($j,0);
		$goGrid->setTotal($j,0);
		}
	$goGrid->showHeadings=false; **/
	$goGrid->externHead=$slHead1;
	$goGrid->setWidth(4, 90);
	$goGrid->setWidth(5, 90);
	$goGrid->setDecPlaces(4,2);
	$goGrid->setDecPlaces(5,2);
	$goGrid->setTotal(4,2);
	$goGrid->setTotal(5,2);	
//	Subtotales
    $goGrid->setOnChange(3, 3);
//    $goGrid->setOnChange(0, 1);
    $goGrid->setSubTotalClass('sub1');
//	echo $goGrid->externHead;
	$goGrid->display();
	ob_end_flush();
?>
